booksapp/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
urlpatterns += [
    path('catalog/', include('catalog.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]



#Add Django site authentication urls (for sign up, login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path(r'oauth/', include('social_django.urls', namespace='social')),
]

catalog/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.decorators import login_required




from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
	path('readedbooks/', views.ReadedBookListView.as_view(), name='readedbooks'),
    path('readedbook/<int:pk>', views.ReadedBookDetailView.as_view(), name='readedbook-detail'),
]

urlpatterns += [
    path('readedbook/create/', views.ReadedBookCreate.as_view(), name='readedbook_create'),
    path('readedbook/<int:pk>/update/', views.ReadedBookUpdate.as_view(), name='readedbook_update'),
    path('readedbook/<int:pk>/delete/', views.ReadedBookDelete.as_view(), name='readedbook_delete'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path(r'borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),  # Added for challenge
]


# Add URLConf for librarian to renew a book.
urlpatterns += [
    path('book/<int:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]


# Add URLConf to create, update, and delete authors
urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

# Add URLConf to create, update, and delete books
urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]


urlpatterns += [
   path(r'^signup/$',  views.signup, name='signup'),
   path(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
   path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
   path(r'^review/$', login_required(views.ReviewList.as_view()), name='review-books'),
   path(r'^review/(?P<pk>[-\w]+)/$', views.review_book, name='review-book'),
]

catalog/models.py
from __future__ import unicode_literals

from django.db.models.signals import post_save
from django.dispatch import receiver

from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.contrib.auth.models import AbstractUser

from django.urls import reverse  # To generate URLS by reversing URL patterns


class Book(models.Model):

    CATAGORY_CHOICES =[
	('Science book', 'Science books'),
	('English book', 'English books'),
	('Biology book', 'Biology books'),
	]
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    cover = models.ImageField(upload_to='books/covers/', null=True,blank=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in file.
    catagory = models.CharField(max_length=200, choices=CATAGORY_CHOICES)
    review = models.TextField(blank=True, null=True)
    reviewed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='reviews')
    date_reviewed = models.DateTimeField(blank=True,null=True)
    is_favourite = models.BooleanField(default=False, verbose_name="Favourite?")

    def display_catagory(self):
        """Creates a string for the Catagory. This is required to display catagory in Admin."""
        return ', '.join([catagory.name for catagory in self.catagory.all()[:3]])

    display_catagory.short_description = 'Catagory'

    def get_absolute_url(self):
        """Returns the url to access a particular readed book."""
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title


from datetime import date

from django.contrib.auth.models import User  # Required to assign User as a borrower


class ReadedBook(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed and read from the from the books Catalog Application)."""
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('readedbook-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.id, self.book.title)


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.last_name, self.first_name)


class User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    email_confirmed = models.BooleanField(default=False)



@receiver(post_save, sender=User)
def update_user (sender, instance, created, **kwargs):
    if created:
        User.objects.create(user=instance)
    instance.user.save()

catalog/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime  # for checking renewal date range.

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Book
from django import forms


class ReviewForm(forms.Form):
    """
    Form for reviewing a book
    """

    is_favourite = forms.BooleanField(
        label="Favourite?",
        help_text="In your top 100",
        required=False,
    )

    review = forms.CharField(
        widget=forms.Textarea,
        min_length=300,
        error_messages={
            'required':'Please enter your review',
            'min_length': 'Please write at least 300 characters (you have written %(show_value)s)'
        }
    )


class RenewBookForm(forms.Form):
    """Form for a Book Catalog to renew books."""
    renewal_date = forms.DateField(
            help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        # Check date is in range book catalog allowed to change (+4 weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'cover', 'catagory', 'reviewed_by']


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/author_confirm_update.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to update the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, update." />
</form>

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Author List</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no authors available.</p>
{% endif %}
        
        
        
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/book_confirm_update.html
{% extends "base_generic.html" %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   <table>
   {{ form.as_table }}
   </table>
    <button type="submit" class="btn btn-primary">Update book</button>
  </form>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
<p><strong>Review:</strong> {{ book.review }}</p>
<p><strong>Catagory:</strong> {% for catagory in book.catagory.all %}{{catagory}}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

<div style="margin-left:20px;margin-top:20px">
<h4>Copies</h4>

{% for copy in book.readedbook_set.all %}
<hr>
<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
{% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
<p><strong>Imprint:</strong> {{copy.imprint}}</p>
<p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>

{% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   <table>
   {{ form.as_table }}
   </table>
    <button type="submit" class="btn btn-primary">Create book</button>
  </form>
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Renew: {{readed_book.book.title}}</h1>
    <p>Readed: {{readed_book.borrower}}</p>
    <p{% if readed_book.is_overdue %} class="text-danger"{% endif %}>Due date: {{readed_book.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalog/templates/catalog/readedbook_detail.html
  
{% extends "base_generic.html" %}

{% block content %}

<h1>Readedbook: {{ readedbook }} </h1>
<p>{{readedbook.due_back}} - {% if readedbook.status %}{{readedbook.status}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Books</h4>

<dl>
{% for book in readedbook.book_set.all %}
  <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.readed_book_set.all.count}})</dt>
  <dd>{{book.catagory}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

catalog/templates/catalog/readedbook_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalog/templates/catalog/readedbook_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Readed Books</h1>

    {% if readedbook_list %}
    <ul>

      {% for readedbooks in readedbook_list %} 
      <li class="{% if readedbooks.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' readedbooks.book.pk %}">{{readedbooks.book.title}}</a> ({{ readedbooks.due_back }}) {% if user.is_staff %}- {{ readedbook.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' readedbooks.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/readedbook_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Readed books</h1>

    {%  if readedbook_list  %}
    <ul>

      {% for readedbooks in readedbook_list%} 
      <li class="{% if readedbooks.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' readedbooks.book.pk %}">{{readedbooks.book.title}}</a> ({{ readedbooks.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no Readed Books.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/review-book.html
{% extends "base_generic.html" %}

{% block content %}
	<h1>Review By <em>{{ book.title }}</em><em>{{ book.list_author }}</em></h1>
    <form method="post">
	{% csrf_token %}

	{% if form.non_field_errors %}
		<div class="non-field-errors">
			{% for error in form.non_field_errors %}
				<span>{{ error }}</span>
			{% endfor %}
		</div>
	{% endif %}

	<label>
		{{ form.is_favourite }} {{ form.is_favourite.label}}
	</label>
	<p><em>{{ form.is_favourite.help_text }}</em></p>

	<div>
		<label>{{ form.review.label }}</label>
		{{ form.review }}
	</div>

	{% if form.review.errors %}
		<div class="form-error">
			{% for error in form.review.errors %}
				<span>{{ error }}</span>
			{% endfor %}
		</div>
	{% endif %}

	<input type="submit" value="Submit Review">
    </form>
{% endblock %}